
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleRaginMage
  name: Ragin Mage Role
  components:
  - type: MindRole
    roleType: TeamAntagonist
    antagPrototype: RaginMage
    exclusiveAntag: true
    subtype: role-subtype-wizard
  - type: WizardRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBloodBrother
  name: Blood Brother Role
  components:
  - type: BloodBrotherRole
  - type: MindRole
    antagPrototype: BloodBrother
    exclusiveAntag: true
    roleType: TeamAntagonist
    subtype: role-subtype-blood-brother
