- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBloodBrother
  name: Blood Brother Role
  components:
  - type: BloodBrotherRole
  - type: MindRole
    antagPrototype: BloodBrother
    exclusiveAntag: true
    roleType: TeamAntagonist
    subtype: role-subtype-blood-brother

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleArcFiend
  name: Arc Fiend Role
  components:
  - type: MindRole
    antagPrototype: Arcfiend
    exclusiveAntag: true
    roleType: TeamAntagonist
    subtype: role-subtype-blood-brother
  - type: ArcfiendRole
