- type: antag
  id: Arcfiend
  name: roles-antag-arcfiend-name
  antagonist: true
  setPreference: true
  objective: roles-antag-arcfiend-objective
  guides: [ Arcfiend ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h
